define("Observable",["Tools"],function(g){function d(){var c={};this.watch=function(a,b,e){if(typeof b=="function"){var f=c[a]=c[a]||[];observer=[b,e];f.push(observer);return[a,f.indexOf(observer)]}else return false};this.unwatch=function(a){var b=a[0],a=a[1];return c[b]&&c[b][a]?(c[b][a]=null,true):false};this.notify=function(a){var b=c[a],e;if(b){for(e=b.length;e--;)b[e]&&b[e][0].apply(b[e][1]||null,g.toArray(arguments).slice(1));return true}else return false};this.hasObserver=function(a){return!(!a||
!c[a[0]]||!c[a[0]][a[1]])};this.unwatchAll=function(){c={};return true}}return{create:function(){return new d}}});
define("StateMachine",function(){function g(){var c={},a="";this.init=function(b){return c[b]?(a=b,true):false};this.add=function(b){return c[b]?false:c[b]=new d};this.get=function(b){return c[b]};this.getCurrent=function(){return a};this.event=function(b,e){var f=c[a].event(b,e);return f===false?false:(a=f||a,true)}}function d(){var c={};this.add=function(a,b,e,f){var d=[];if(c[a])return false;return typeof a=="string"&&typeof b=="function"?(d[0]=b,typeof e=="object"&&(d[1]=e),typeof e=="string"&&
(d[2]=e),typeof f=="string"&&(d[2]=f),c[a]=d,true):false};this.has=function(a){return!!c[a]};this.event=function b(b,e){var f=c[b];return f?(f[0].call(f[1],e),f[2]):false}}return{create:function(d,a){var b=new g,e,f;for(e in a)a.hasOwnProperty(e)&&(f=b.add(e),a[e].forEach(function(b){f.add.apply(null,b)}));b.init(d);return b}}});
define("TinyStore",["Observable","Tools"],function(g,d){function c(a){var b=a||{},e=g.create();this.getNbItems=function(){return d.count(b)};this.get=function(a){return b[a]};this.has=function(a){return b.hasOwnProperty(a)};this.set=function(a,d){var c;return typeof a!="undefined"?(c=this.has(a),b[a]=d,c?e.notify("updated",a,d):e.notify("added",a,d),true):false};this.del=function(a){return this.has(a)?(delete b[a],e.notify("deleted",a,b[a]),true):false};this.watch=function(a,b,d){return e.watch(a,
b,d)};this.unwatch=function(a){return e.unwatch(a)};this.loop=function(a,d){if(b.forEach)b.forEach(a,d);else for(var c in b)b.hasOwnProperty(c)&&a.call(d,b[c],c)};this.reset=function(a){return a instanceof Object?(b=a,e.notify("reset"),true):false}}return{create:function(a){return new c(a)}}});
define("Tools",function(){return{getGlobal:function(){return function(){return this}.call(null)},mixin:function(g,d,c){for(var a in g)if(g.hasOwnProperty(a)&&(!d[a]||!c))d[a]=g[a]},count:function(g){var d=0,c;for(c in g)g.hasOwnProperty(c)&&d++;return d},compareObjects:function(g,d){return Object.getOwnPropertyNames(g).sort().join("")==Object.getOwnPropertyNames(d).sort().join("")},toArray:function(g){return Array.prototype.slice.call(g)}}});
define("Transport",function(){function g(){var d,c=io;this.connect=function(a){d=c.connect(a);return!!d};this.getSocket=function(){return d};this.on=function(a,b){d.on(a,b)};this.once=function(a,b){d.once(a,b)};this.emit=function(a,b,c){d.emit(a,b,c)};this.request=function(a,b,c){var f=+new Date+Math.floor(Math.random()*1E6);d.once(f,c);b.__eventId__=f;d.emit(a,b)};this.listen=function(a,b,c){var f=+new Date+Math.floor(Math.random()*1E6);d.on(f,c);b.__eventId__=f;d.emit(a,b);return{stop:function(){d.removeListener(f,
c)}}}}return{create:function(d){var c=new g(d);c.connect(d);return c}}});
