define("CouchDBStore",["Store","StateMachine","Tools","Promise"],function(d,f,e,c){function b(){var b=null,a=null,k=null,e=null,d=null,i={},j=new c,h=new f("Unsynched",{Unsynched:[["getView",function(){b.request("CouchDB",{method:"GET",path:"/"+a+"/_design/"+d+"/_view/"+k+"?update_seq=true"},function(a){a=JSON.parse(a);i={total_rows:a.total_rows,update_seq:a.update_seq,offset:a.offset};this.reset(a.rows);h.event("subscribeToViewChanges",a.update_seq)},this)},this,"Synched"],["getDocument",function(){b.request("CouchDB",
{method:"GET",path:"/"+a+"/"+e},function(a){a=JSON.parse(a);a._id?(this.reset(a),h.event("subscribeToDocumentChanges")):j.reject(this)},this)},this,"Synched"]],Synched:[["updateDatabase",function(){b.request("CouchDB",{method:"PUT",path:"/"+a+"/"+e,headers:{"Content-Type":"application/json"},data:this.toJSON()},function(){h.event("subscribeToDocumentChanges")})},this],["subscribeToViewChanges",function(c){b.listen("CouchDB","/"+a+"/_changes?feed=continuous&heartbeat=20000&since="+c,function(a){if(a==
"\n")return false;var a=JSON.parse(a),b;b=a.deleted?"delete":a.changes[0].rev.search("1-")==0?"add":"change";h.event(b,a.id)},this)},this,"Listening"],["subscribeToDocumentChanges",function(){b.listen("CouchDB","/"+a+"/_changes?feed=continuous&heartbeat=20000",function(a){if(a=="\n")return false;a=JSON.parse(a);a.id==e&&a.changes.pop().rev!=this.get("_rev")&&(a.deleted?h.event("deleteDoc"):h.event("updateDoc"))},this)},this,"Listening"]],Listening:[["entry",function(){j.resolve(this)},this],["change",
function(c){b.request("CouchDB",{method:"GET",path:"/"+a+"/_design/"+d+"/_view/"+k},function(a){JSON.parse(a).rows.some(function(a,b){a.id==c&&this.set(b,a)},this)},this)},this],["delete",function(a){this.loop(function(b,c){b.id==a&&this.del(c)},this)},this],["add",function(c){b.request("CouchDB",{method:"GET",path:"/"+a+"/_design/"+d+"/_view/"+k},function(a){JSON.parse(a).rows.some(function(a,b){a.id==c&&this.alter("splice",b,0,a)},this)},this)},this],["updateDoc",function(){b.request("CouchDB",
{method:"GET",path:"/"+a+"/"+e},function(a){this.reset(JSON.parse(a))},this)},this],["deleteDoc",function(){this.reset({})},this],["updateDatabase",function(){b.request("CouchDB",{method:"PUT",path:"/"+a+"/"+e,headers:{"Content-Type":"application/json"},data:this.toJSON()})},this],["removeFromDatabase",function(){b.request("CouchDB",{method:"DELETE",path:"/"+a+"/"+e+"?rev="+this.get("_rev")})},this]]});this.sync=function(b,c,f){if(typeof b=="string"&&typeof c=="string"&&typeof f=="string")return a=
b,d=c,k=f,h.event("getView"),j;else if(typeof b=="string"&&typeof c=="string"&&typeof f=="undefined")return a=b,e=c,h.event("getDocument"),j;return false};this.update=function(){return h.event("updateDatabase")};this.remove=function(){return h.event("removeFromDatabase")};this.getDBInfo=function(a){return i[a]};this.setTransport=function(a){return a&&typeof a.listen=="function"&&typeof a.request=="function"?(b=a,true):false};this.getStateMachine=function(){return h};this.getTransport=function(){return b}}
return function(){b.prototype=new d;return new b}});
define("Observable",["Tools"],function(d){return function(){var f={};this.watch=function(e,c,b){if(typeof c=="function"){var d=f[e]=f[e]||[];observer=[c,b];d.push(observer);return[e,d.indexOf(observer)]}else return false};this.unwatch=function(e){var c=e[0],e=e[1];return f[c]&&f[c][e]?(delete f[c][e],f[c].some(function(b){return!!b})||delete f[c],true):false};this.notify=function(e){var c=f[e],b;if(c){for(b=c.length;b--;)c[b]&&c[b][0].apply(c[b][1]||null,d.toArray(arguments).slice(1));return true}else return false};
this.hasObserver=function(e){return!(!e||!f[e[0]]||!f[e[0]][e[1]])};this.hasTopic=function(e){return!!f[e]};this.unwatchAll=function(e){f[e]?delete f[e]:f={};return true}}});
define("Promise",["Observable","StateMachine"],function(d,f){return function(){var e,c,b=new f("Unresolved",{Unresolved:[["resolve",function(a){e=a;g.notify("success",a)},"Resolved"],["reject",function(a){c=a;g.notify("fail",a)},"Rejected"],["addSuccess",function(a,b){g.watch("success",a,b)}],["addFail",function(a,b){g.watch("fail",a,b)}]],Resolved:[["addSuccess",function(a,b){a.call(b,e)}]],Rejected:[["addFail",function(a,b){a.call(b,c)}]]}),g=new d;this.resolve=function(a){return b.event("resolve",
a)};this.reject=function(a){return b.event("reject",a)};this.then=function(a,c,e,d){a instanceof Function&&(c instanceof Function?b.event("addSuccess",a):b.event("addSuccess",a,c));c instanceof Function&&b.event("addFail",c,e);e instanceof Function&&b.event("addFail",e,d);return this};this.getObservable=function(){return g};this.getStateMachine=function(){return b}}});
define("StateMachine",["Tools"],function(d){function f(){var e={};this.add=function(c,b,d,a){var f=[];if(e[c])return false;return typeof c=="string"&&typeof b=="function"?(f[0]=b,typeof d=="object"&&(f[1]=d),typeof d=="string"&&(f[2]=d),typeof a=="string"&&(f[2]=a),e[c]=f,true):false};this.has=function(c){return!!e[c]};this.event=function b(b){var f=e[b];return f?(f[0].apply(f[1],d.toArray(arguments).slice(1)),f[2]):false}}return function(e,c){var b={},g="";this.init=function(a){return b[a]?(g=a,
true):false};this.add=function(a){return b[a]?false:b[a]=new f};this.get=function(a){return b[a]};this.getCurrent=function(){return g};this.event=function(a){var c;c=b[g].event.apply(b[g].event,d.toArray(arguments));return c===false?false:(c&&(b[g].event("exit"),g=c,b[g].event("entry")),true)};d.loop(c,function(a,b){var c=this.add(b);a.forEach(function(a){c.add.apply(null,a)})},this);this.init(e)}});
define("Store",["Observable","Tools"],function(d,f){return function(e){var c=f.clone(e)||{},b=new d,g=function(a){var d=f.objectsDiffs(a,c);["updated","deleted","added"].forEach(function(a){d[a].forEach(function(d){b.notify(a,d,c[d])})})};this.getNbItems=function(){return c instanceof Array?c.length:f.count(c)};this.get=function(a){return c[a]};this.has=function(a){return c.hasOwnProperty(a)};this.set=function(a,d){var e;return typeof a!="undefined"?(e=this.has(a),c[a]=d,e?b.notify("updated",a,c[a]):
b.notify("added",a,c[a]),true):false};this.del=function(a){return this.has(a)?(this.alter("splice",a,1)||(delete c[a],b.notify("deleted",a)),true):false};this.alter=function(a){var b,d;return c[a]?(d=f.clone(c),b=c[a].apply(c,Array.prototype.slice.call(arguments,1)),g(d),b):false};this.watch=function(a,c,d){return b.watch(a,c,d)};this.unwatch=function(a){return b.unwatch(a)};this.loop=function(a,b){f.loop(c,a,b)};this.reset=function(a){if(a instanceof Object){var b=f.clone(c);c=f.clone(a)||{};g(b);
return true}else return false};this.toJSON=function(){return JSON.stringify(c)}}});
define("Tools",function(){return{getGlobal:function(){return function(){return this}.call(null)},mixin:function(d,f,e){this.loop(d,function(c,b){if(!f[b]||!e)f[b]=d[b]});return f},count:function(d){var f=0;this.loop(d,function(){f++});return f},compareObjects:function(d,f){return Object.getOwnPropertyNames(d).sort().join("")==Object.getOwnPropertyNames(f).sort().join("")},toArray:function(d){return Array.prototype.slice.call(d)},loop:function(d,f,e){var c,b;if(d instanceof Object&&typeof f=="function"){if(b=
d.length)for(c=0;c<b;c++)f.call(e,d[c],c,d);else for(c in d)d.hasOwnProperty(c)&&f.call(e,d[c],c,d);return true}else return false},objectsDiffs:function(d,f){if(d instanceof Object&&f instanceof Object){var e=[],c=[],b=[],g=[];this.loop(f,function(a,b){a!==d[b]&&typeof d[b]!="undefined"?c.push(b):a===d[b]?e.push(b):typeof d[b]=="undefined"&&g.push(b)});this.loop(d,function(a,c){typeof f[c]=="undefined"&&b.push(c)});return{updated:c,unchanged:e,added:g,deleted:b}}else return false},jsonify:function(d){return d instanceof
Object?JSON.parse(JSON.stringify(d)):false},clone:function(d){return d instanceof Array?d.slice(0):typeof d=="object"&&d!==null&&!(d instanceof RegExp)?this.mixin(d,{}):d},getObjectsProperty:function(d,f){if(d&&d instanceof Object&&typeof f=="string"&&f!=""){var e=f.split(".");e.unshift(d);return e.reduce(function(c,b){return c[b]})}else return d}}});
define("Transport",["Observable"],function(d){return function(f){var e=null,c=io,b=new d;this.connect=function(b){e=c.connect(b);return!!e};this.getSocket=function(){return e};this.on=function(b,a){e.on(b,a)};this.once=function(b,a){e.once(b,a)};this.emit=function(b,a,c){e.emit(b,a,c)};this.request=function(b,a,c,d){var f=Date.now()+Math.floor(Math.random()*1E6),i=function(){c&&c.apply(d||null,arguments)};e[a.keptAlive?"on":"once"](f,i);a.__eventId__=f;e.emit(b,a);if(a.keptAlive)return function(){e.removeListener(f,
i)}};this.listen=function(c,a,d,f){var e=c+"/"+a,i,j;b.hasTopic(e)||(j=this.request(c,{path:a,method:"GET",keptAlive:true},function(a){b.notify(e,a)},this));i=b.watch(e,d,f);return{stop:function(){b.unwatch(i);b.hasTopic(e)||j()}}};this.getListenObservable=function(){return b};this.connect(f)}});
