/*
 Emily

 The MIT License (MIT)

 Copyright (c) 2012 Olivier Scherrer <pode.fr@gmail.com>

 Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated 
 documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, 
 and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or substantial 
 portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
define("CouchDBStore",["Store","StateMachine","Tools","Promise"],function(a,e,f,d){function c(){var a=null,h=null,b=null,c=null,f=null,j={},k=new d,i=new e("Unsynched",{Unsynched:[["getView",function(){a.request("CouchDB",{method:"GET",path:"/"+h+"/_design/"+f+"/_view/"+b+"?update_seq=true"},function(b){b=JSON.parse(b);j={total_rows:b.total_rows,update_seq:b.update_seq,offset:b.offset};this.reset(b.rows);i.event("subscribeToViewChanges",b.update_seq)},this)},this,"Synched"],["getDocument",function(){a.request("CouchDB",
{method:"GET",path:"/"+h+"/"+c},function(b){b=JSON.parse(b);b._id?(this.reset(b),i.event("subscribeToDocumentChanges")):k.reject(this)},this)},this,"Synched"]],Synched:[["updateDatabase",function(){a.request("CouchDB",{method:"PUT",path:"/"+h+"/"+c,headers:{"Content-Type":"application/json"},data:this.toJSON()},function(){i.event("subscribeToDocumentChanges")})},this],["subscribeToViewChanges",function(b){a.listen("CouchDB","/"+h+"/_changes?feed=continuous&heartbeat=20000&since="+b,function(b){if(b==
"\n")return false;var b=JSON.parse(b),a;a=b.deleted?"delete":b.changes[0].rev.search("1-")==0?"add":"change";i.event(a,b.id)},this)},this,"Listening"],["subscribeToDocumentChanges",function(){a.listen("CouchDB","/"+h+"/_changes?feed=continuous&heartbeat=20000",function(b){if(b=="\n")return false;b=JSON.parse(b);b.id==c&&b.changes.pop().rev!=this.get("_rev")&&(b.deleted?i.event("deleteDoc"):i.event("updateDoc"))},this)},this,"Listening"]],Listening:[["entry",function(){k.resolve(this)},this],["change",
function(c){a.request("CouchDB",{method:"GET",path:"/"+h+"/_design/"+f+"/_view/"+b},function(b){JSON.parse(b).rows.some(function(b,a){b.id==c&&this.set(a,b)},this)},this)},this],["delete",function(b){this.loop(function(a,c){a.id==b&&this.del(c)},this)},this],["add",function(c){a.request("CouchDB",{method:"GET",path:"/"+h+"/_design/"+f+"/_view/"+b},function(b){JSON.parse(b).rows.some(function(b,a){b.id==c&&this.alter("splice",a,0,b)},this)},this)},this],["updateDoc",function(){a.request("CouchDB",
{method:"GET",path:"/"+h+"/"+c},function(b){this.reset(JSON.parse(b))},this)},this],["deleteDoc",function(){this.reset({})},this],["updateDatabase",function(){a.request("CouchDB",{method:"PUT",path:"/"+h+"/"+c,headers:{"Content-Type":"application/json"},data:this.toJSON()})},this],["removeFromDatabase",function(){a.request("CouchDB",{method:"DELETE",path:"/"+h+"/"+c+"?rev="+this.get("_rev")})},this]]});this.sync=function(a,d,e){if(typeof a=="string"&&typeof d=="string"&&typeof e=="string")return h=
a,f=d,b=e,i.event("getView"),k;else if(typeof a=="string"&&typeof d=="string"&&typeof e=="undefined")return h=a,c=d,i.event("getDocument"),k;return false};this.update=function(){return i.event("updateDatabase")};this.remove=function(){return i.event("removeFromDatabase")};this.getDBInfo=function(b){return j[b]};this.setTransport=function(b){return b&&typeof b.listen=="function"&&typeof b.request=="function"?(a=b,true):false};this.getStateMachine=function(){return i};this.getTransport=function(){return a}}
return function(){c.prototype=new a;return new c}});
define("Observable",["Tools"],function(a){return function(){var e={};this.watch=function(a,d,c){if(typeof d=="function"){var g=e[a]=e[a]||[];observer=[d,c];g.push(observer);return[a,g.indexOf(observer)]}else return false};this.unwatch=function(a){var d=a[0],a=a[1];return e[d]&&e[d][a]?(delete e[d][a],e[d].some(function(a){return!!a})||delete e[d],true):false};this.notify=function(f){var d=e[f],c;if(d){for(c=d.length;c--;)d[c]&&d[c][0].apply(d[c][1]||null,a.toArray(arguments).slice(1));return true}else return false};
this.hasObserver=function(a){return!(!a||!e[a[0]]||!e[a[0]][a[1]])};this.hasTopic=function(a){return!!e[a]};this.unwatchAll=function(a){e[a]?delete e[a]:e={};return true}}});
define("Promise",["Observable","StateMachine"],function(a,e){return function(){var f,d,c=new e("Unresolved",{Unresolved:[["resolve",function(a){f=a;g.notify("success",a)},"Resolved"],["reject",function(a){d=a;g.notify("fail",a)},"Rejected"],["addSuccess",function(a,b){g.watch("success",a,b)}],["addFail",function(a,b){g.watch("fail",a,b)}]],Resolved:[["addSuccess",function(a,b){a.call(b,f)}]],Rejected:[["addFail",function(a,b){a.call(b,d)}]]}),g=new a;this.resolve=function(a){return c.event("resolve",
a)};this.reject=function(a){return c.event("reject",a)};this.then=function(a,b,d,e){a instanceof Function&&(b instanceof Function?c.event("addSuccess",a):c.event("addSuccess",a,b));b instanceof Function&&c.event("addFail",b,d);d instanceof Function&&c.event("addFail",d,e);return this};this.getObservable=function(){return g};this.getStateMachine=function(){return c}}});
define("StateMachine",["Tools"],function(a){function e(){var e={};this.add=function(a,c,g,h){var b=[];if(e[a])return false;return typeof a=="string"&&typeof c=="function"?(b[0]=c,typeof g=="object"&&(b[1]=g),typeof g=="string"&&(b[2]=g),typeof h=="string"&&(b[2]=h),e[a]=b,true):false};this.has=function(a){return!!e[a]};this.event=function c(c){var g=e[c];return g?(g[0].apply(g[1],a.toArray(arguments).slice(1)),g[2]):false}}return function(f,d){var c={},g="";this.init=function(a){return c[a]?(g=a,
true):false};this.add=function(a){return c[a]?false:c[a]=new e};this.get=function(a){return c[a]};this.getCurrent=function(){return g};this.event=function(d){var b;b=c[g].event.apply(c[g].event,a.toArray(arguments));return b===false?false:(b&&(c[g].event("exit"),g=b,c[g].event("entry")),true)};a.loop(d,function(a,b){var c=this.add(b);a.forEach(function(a){c.add.apply(null,a)})},this);this.init(f)}});
define("Store",["Observable","Tools"],function(a,e){return function(f){var d=e.clone(f)||{},c=new a,g=new a,h=function(a){var f=e.objectsDiffs(a,d);["updated","deleted","added"].forEach(function(a){f[a].forEach(function(b){c.notify(a,b,d[b]);g.notify(b,d[b],a)})})};this.getNbItems=function(){return d instanceof Array?d.length:e.count(d)};this.get=function(a){return d[a]};this.has=function(a){return d.hasOwnProperty(a)};this.set=function(a,e){var f;return typeof a!="undefined"?(f=this.has(a),d[a]=
e,f=f?"updated":"added",c.notify(f,a,d[a]),g.notify(a,d[a],f),true):false};this.del=function(a){return this.has(a)?(this.alter("splice",a,1)||(delete d[a],c.notify("deleted",a),g.notify(a,d[a],"deleted")),true):false};this.alter=function(a){var c,g;return d[a]?(g=e.clone(d),c=d[a].apply(d,Array.prototype.slice.call(arguments,1)),h(g),c):false};this.watch=function(a,d,e){return c.watch(a,d,e)};this.unwatch=function(a){return c.unwatch(a)};this.getStoreObservable=function(){return c};this.watchValue=
function(a,c,d){return g.watch(a,c,d)};this.unwatchValue=function(a){return g.unwatch(a)};this.getValueObservable=function(){return g};this.loop=function(a,c){e.loop(d,a,c)};this.reset=function(a){if(a instanceof Object){var c=e.clone(d);d=e.clone(a)||{};h(c);return true}else return false};this.toJSON=function(){return JSON.stringify(d)}}});
define("Tools",function(){return{getGlobal:function(){return function(){return this}.call(null)},mixin:function(a,e,f){this.loop(a,function(d,c){if(!e[c]||!f)e[c]=a[c]});return e},count:function(a){var e=0;this.loop(a,function(){e++});return e},compareObjects:function(a,e){return Object.getOwnPropertyNames(a).sort().join("")==Object.getOwnPropertyNames(e).sort().join("")},toArray:function(a){return Array.prototype.slice.call(a)},loop:function(a,e,f){var d,c;if(a instanceof Object&&typeof e=="function"){if(c=
a.length)for(d=0;d<c;d++)e.call(f,a[d],d,a);else for(d in a)a.hasOwnProperty(d)&&e.call(f,a[d],d,a);return true}else return false},objectsDiffs:function(a,e){if(a instanceof Object&&e instanceof Object){var f=[],d=[],c=[],g=[];this.loop(e,function(c,b){c!==a[b]&&typeof a[b]!="undefined"?d.push(b):c===a[b]?f.push(b):typeof a[b]=="undefined"&&g.push(b)});this.loop(a,function(a,b){typeof e[b]=="undefined"&&c.push(b)});return{updated:d,unchanged:f,added:g,deleted:c}}else return false},jsonify:function(a){return a instanceof
Object?JSON.parse(JSON.stringify(a)):false},clone:function(a){return a instanceof Array?a.slice(0):typeof a=="object"&&a!==null&&!(a instanceof RegExp)?this.mixin(a,{}):a},getNestedProperty:function(a,e){if(a&&a instanceof Object)if(typeof e=="string"&&e!=""){var f=e.split(".");f.unshift(a);return f.reduce(function(a,c){return a[c]})}else return typeof e=="number"?a[e]:a;else return a},setNestedProperty:function(a,e,f){if(a&&a instanceof Object)if(typeof e=="string"&&e!=""){var d=e.split(".");d.unshift(a);
return d.reduce(function(a,e,h){d.length==h+1&&(a[e]=f);return a[e]})}else return typeof e=="number"?(a[e]=f,a[e]):a;else return a}}});
define("Transport",["Observable"],function(a){return function(e){var f=null,d=io,c=new a;this.connect=function(a){f=d.connect(a);return!!f};this.getSocket=function(){return f};this.on=function(a,c){f.on(a,c)};this.once=function(a,c){f.once(a,c)};this.emit=function(a,c,b){f.emit(a,c,b)};this.request=function(a,c,b,e){var d=Date.now()+Math.floor(Math.random()*1E6),j=function(){b&&b.apply(e||null,arguments)};f[c.keptAlive?"on":"once"](d,j);c.__eventId__=d;f.emit(a,c);if(c.keptAlive)return function(){f.removeListener(d,
j)}};this.listen=function(a,d,b,e){var f=a+"/"+d,j,k;c.hasTopic(f)||(k=this.request(a,{path:d,method:"GET",keptAlive:true},function(a){c.notify(f,a)},this));j=c.watch(f,b,e);return{stop:function(){c.unwatch(j);c.hasTopic(f)||k()}}};this.getListenObservable=function(){return c};this.connect(e)}});
