define("CouchDBStore",["Store","StateMachine","Tools"],function(d,e){function c(){var a=null,f=null,c=null,b=null,h=null,d={},i=new e("Unsynched",{Unsynched:[["getView",function(){a.request("CouchDB",{method:"GET",path:"/"+f+"/_design/"+h+"/_view/"+c+"?update_seq=true"},function(b){b=JSON.parse(b);d={total_rows:b.total_rows,update_seq:b.update_seq,offset:b.offset};this.reset(b.rows);i.event("subscribeToViewChanges",b.update_seq)},this)},this,"Synched"],["getDocument",function(){a.request("CouchDB",
{method:"GET",path:"/"+f+"/"+b},function(b){this.reset(JSON.parse(b));i.event("subscribeToDocumentChanges")},this)},this,"Synched"]],Synched:[["subscribeToViewChanges",function(b){a.listen("CouchDB","/"+f+"/_changes?feed=continuous&heartbeat=20000&since="+b,function(b){if(b=="\n")return false;var b=JSON.parse(b),a;a=b.deleted?"delete":b.changes[0].rev.search("1-")==0?"add":"change";i.event(a,b.id)},this)},this,"Listening"],["subscribeToDocumentChanges",function(){a.listen("CouchDB","/"+f+"/_changes?feed=continuous&heartbeat=20000",
function(a){if(a=="\n")return false;a=JSON.parse(a);a.id==b&&(a.deleted?i.event("deleteDoc"):i.event("updateDoc"))},this)},this,"Listening"]],Listening:[["change",function(b){a.request("CouchDB",{method:"GET",path:"/"+f+"/_design/"+h+"/_view/"+c},function(a){JSON.parse(a).rows.some(function(a,c){a.id==b&&this.set(c,a)},this)},this)},this],["delete",function(b){this.loop(function(a,c){a.id==b&&this.del(c)},this)},this],["add",function(b){a.request("CouchDB",{method:"GET",path:"/"+f+"/_design/"+h+"/_view/"+
c},function(a){JSON.parse(a).rows.some(function(a,c){a.id==b&&this.alter("splice",c,0,a)},this)},this)},this],["updateDoc",function(){a.request("CouchDB",{method:"GET",path:"/"+f+"/"+b},function(b){this.reset(JSON.parse(b))},this)},this],["deleteDoc",function(){this.reset({})},this]]});this.sync=function(a,d,e){if(typeof a=="string"&&typeof d=="string"&&typeof e=="string")return f=a,h=d,c=e,i.event("getView"),true;else if(typeof a=="string"&&typeof d=="string"&&typeof e=="undefined")return f=a,b=
d,i.event("getDocument"),true;return false};this.getDBInfo=function(b){return d[b]};this.setTransport=function(b){return b&&typeof b.listen=="function"&&typeof b.request=="function"?(a=b,true):false};this.getState=function(){return i.getCurrent()};this.getTransport=function(){return a}}return function(){c.prototype=new d;return new c}});
define("Observable",["Tools"],function(d){return function(){var e={};this.watch=function(c,a,d){if(typeof a=="function"){var g=e[c]=e[c]||[];observer=[a,d];g.push(observer);return[c,g.indexOf(observer)]}else return false};this.unwatch=function(c){var a=c[0],c=c[1];return e[a]&&e[a][c]?(delete e[a][c],e[a].some(function(a){return!!a})||delete e[a],true):false};this.notify=function(c){var a=e[c],f;if(a){for(f=a.length;f--;)a[f]&&a[f][0].apply(a[f][1]||null,d.toArray(arguments).slice(1));return true}else return false};
this.hasObserver=function(c){return!(!c||!e[c[0]]||!e[c[0]][c[1]])};this.hasTopic=function(c){return!!e[c]};this.unwatchAll=function(c){e[c]?delete e[c]:e={};return true}}});
define("Promise",["StateMachine","Observable","Tools"],function(d,e,c){return function(a,f){var g=null,b=null,h=null,k=null,i=new e;_stateMachine=new d("Unresolved",{Unresolved:[["resolve",function(){g.call(b,function(){return _stateMachine.event.apply(_stateMachine,c.toArray(arguments))})}],["success",function(b){h=b;i.notify("success",b)},"Resolved"],["fail",function(b){k=b;i.notify("fail",b)},"Failed"],["addThen",function(b,a,c){i.watch(b,a,c)}]],Resolved:[["addThen",function(b,a,c){a.call(c,b==
"success"?h:k)}]],Failed:[["addThen",function(b,a,c){a.call(c,b=="success"?h:k)}]]});this.then=function(b,a,c,d){b instanceof Function&&(a instanceof Function?_stateMachine.event("addThen","success",a):_stateMachine.event("addThen","success",b,a));a instanceof Function&&_stateMachine.event("addThen","fail",a,c);c instanceof Function&&_stateMachine.event("addThen","fail",c,d)};this.resolve=function(){return!(!g||!_stateMachine.event("resolve"))};this.getState=function(){return _stateMachine.getCurrent()};
a instanceof Function&&(g=a,b=f)}});
define("StateMachine",["Tools"],function(d){function e(){var c={};this.add=function(a,d,e,b){var h=[];if(c[a])return false;return typeof a=="string"&&typeof d=="function"?(h[0]=d,typeof e=="object"&&(h[1]=e),typeof e=="string"&&(h[2]=e),typeof b=="string"&&(h[2]=b),c[a]=h,true):false};this.has=function(a){return!!c[a]};this.event=function f(f){var e=c[f];return e?(e[0].apply(e[1],d.toArray(arguments).slice(1)),e[2]):false}}return function(c,a){var f={},g="";this.init=function(b){return f[b]?(g=b,
true):false};this.add=function(b){return f[b]?false:f[b]=new e};this.get=function(b){return f[b]};this.getCurrent=function(){return g};this.event=function(b){var a=f[g].event.apply(f[g].event,d.toArray(arguments));return a===false?false:(g=a||g,true)};d.loop(a,function(b,a){var c=this.add(a);b.forEach(function(b){c.add.apply(null,b)})},this);this.init(c)}});
define("Store",["Observable","Tools"],function(d,e){return function(c){var a=e.clone(c)||{},f=new d,g=function(b){var c=e.objectsDiffs(b,a);["updated","deleted","added"].forEach(function(b){c[b].forEach(function(c){f.notify(b,c,a[c])})})};this.getNbItems=function(){return a instanceof Array?a.length:e.count(a)};this.get=function(b){return a[b]};this.has=function(b){return a.hasOwnProperty(b)};this.set=function(b,c){var d;return typeof b!="undefined"?(d=this.has(b),a[b]=c,d?f.notify("updated",b,a[b]):
f.notify("added",b,a[b]),true):false};this.del=function(b){return this.has(b)?(this.alter("splice",b,1)||(delete a[b],f.notify("deleted",b)),true):false};this.alter=function(b){var c,d;return a[b]?(d=e.clone(a),c=a[b].apply(a,Array.prototype.slice.call(arguments,1)),g(d),c):false};this.watch=function(b,a,c){return f.watch(b,a,c)};this.unwatch=function(b){return f.unwatch(b)};this.loop=function(b,c){e.loop(a,b,c)};this.reset=function(b){if(b instanceof Object){var c=e.clone(a);a=e.clone(b)||{};g(c);
return true}else return false}}});
define("Tools",function(){return{getGlobal:function(){return function(){return this}.call(null)},mixin:function(d,e,c){this.loop(d,function(a,f){if(!e[f]||!c)e[f]=d[f]});return e},count:function(d){var e=0;this.loop(d,function(){e++});return e},compareObjects:function(d,e){return Object.getOwnPropertyNames(d).sort().join("")==Object.getOwnPropertyNames(e).sort().join("")},toArray:function(d){return Array.prototype.slice.call(d)},loop:function(d,e,c){var a;if(d instanceof Object&&typeof e=="function"){if(d instanceof
Array)d.forEach(e,c);else for(a in d)d.hasOwnProperty(a)&&e.call(c,d[a],a,d);return true}else return false},objectsDiffs:function(d,e){if(d instanceof Object&&e instanceof Object){var c=[],a=[],f=[],g=[];this.loop(e,function(b,e){b!==d[e]&&typeof d[e]!="undefined"?a.push(e):b===d[e]?c.push(e):typeof d[e]=="undefined"&&g.push(e)});this.loop(d,function(b,a){typeof e[a]=="undefined"&&f.push(a)});return{updated:a,unchanged:c,added:g,deleted:f}}else return false},jsonify:function(d){return d instanceof
Object?JSON.parse(JSON.stringify(d)):false},clone:function(d){return d instanceof Array?d.slice(0):typeof d=="object"&&d!==null&&!(d instanceof RegExp)?this.mixin(d,{}):d}}});
define("Transport",["Observable"],function(d){return function(e){var c,a=io,f=new d;this.connect=function(d){c=a.connect(d);return!!c};this.getSocket=function(){return c};this.on=function(a,b){c.on(a,b)};this.once=function(a,b){c.once(a,b)};this.emit=function(a,b,d){c.emit(a,b,d)};this.request=function(a,b,d,e){var f=Date.now()+Math.floor(Math.random()*1E6),j=function(){d.apply(e||null,arguments)};c[b.keptAlive?"on":"once"](f,j);b.__eventId__=f;c.emit(a,b);if(b.keptAlive)return function(){c.removeListener(f,
j)}};this.listen=function(a,b,c,d){var e=a+"/"+b,j,l;f.hasTopic(e)||(l=this.request(a,{path:b,method:"GET",keptAlive:true},function(a){f.notify(e,a)},this));j=f.watch(e,c,d);return{stop:function(){f.unwatch(j);f.hasTopic(e)||l()}}};this.getListenObservable=function(){return f};this.connect(e)}});
