define("CouchDBStore",["Store","StateMachine","Tools"],function(c,d){function b(){var a=null,f=null,b=null,e=null,c=null,i={},g=new d("Unsynched",{Unsynched:[["getView",function(){a.request("CouchDB",{method:"GET",path:"/"+f+"/_design/"+c+"/_view/"+b+"?update_seq=true"},function(a){a=JSON.parse(a);i={total_rows:a.total_rows,update_seq:a.update_seq,offset:a.offset};this.reset(a.rows);g.event("subscribeToViewChanges",a.update_seq)},this)},this,"Synched"],["getDocument",function(){a.request("CouchDB",
{method:"GET",path:"/"+f+"/"+e},function(a){this.reset(JSON.parse(a));g.event("subscribeToDocumentChanges")},this)},this,"Synched"]],Synched:[["subscribeToViewChanges",function(e){a.listen("CouchDB","/"+f+"/_changes?feed=continuous&heartbeat=20000&since="+e,function(a){if(a=="\n")return false;var a=JSON.parse(a),e;e=a.deleted?"delete":a.changes[0].rev.search("1-")==0?"add":"change";g.event(e,a.id)},this)},this,"Listening"],["subscribeToDocumentChanges",function(){a.listen("CouchDB","/"+f+"/_changes?feed=continuous&heartbeat=20000",
function(a){if(a=="\n")return false;a=JSON.parse(a);a.id==e&&(a.deleted?g.event("deleteDoc"):g.event("updateDoc"))},this)},this,"Listening"]],Listening:[["change",function(e){a.request("CouchDB",{method:"GET",path:"/"+f+"/_design/"+c+"/_view/"+b},function(a){JSON.parse(a).rows.some(function(a,b){a.id==e&&this.set(b,a)},this)},this)},this],["delete",function(a){this.loop(function(e,b){e.id==a&&this.del(b)},this)},this],["add",function(e){a.request("CouchDB",{method:"GET",path:"/"+f+"/_design/"+c+"/_view/"+
b},function(a){JSON.parse(a).rows.some(function(a,b){a.id==e&&this.alter("splice",b,0,a)},this)},this)},this],["updateDoc",function(){a.request("CouchDB",{method:"GET",path:"/"+f+"/"+e},function(a){this.reset(JSON.parse(a))},this)},this],["deleteDoc",function(){this.reset({})},this]]});this.sync=function(a,d,i){if(typeof a=="string"&&typeof d=="string"&&typeof i=="string")return f=a,c=d,b=i,g.event("getView"),true;else if(typeof a=="string"&&typeof d=="string"&&typeof i=="undefined")return f=a,e=
d,g.event("getDocument"),true;return false};this.getDBInfo=function(a){return i[a]};this.setTransport=function(e){return e&&typeof e.listen=="function"&&typeof e.request=="function"?(a=e,true):false};this.getState=function(){return g.getCurrent()};this.getTransport=function(){return a}}return function(){b.prototype=new c;return new b}});
define("Observable",["Tools"],function(c){return function(){var d={};this.watch=function(b,a,f){if(typeof a=="function"){var c=d[b]=d[b]||[];observer=[a,f];c.push(observer);return[b,c.indexOf(observer)]}else return false};this.unwatch=function(b){var a=b[0],b=b[1];return d[a]&&d[a][b]?(delete d[a][b],d[a].some(function(a){return!!a})||delete d[a],true):false};this.notify=function(b){var a=d[b],f;if(a){for(f=a.length;f--;)a[f]&&a[f][0].apply(a[f][1]||null,c.toArray(arguments).slice(1));return true}else return false};
this.hasObserver=function(b){return!(!b||!d[b[0]]||!d[b[0]][b[1]])};this.hasTopic=function(b){return!!d[b]};this.unwatchAll=function(b){d[b]?delete d[b]:d={};return true}}});
define("Promise",["StateMachine","Observable","Tools"],function(c,d,b){return function(a,f){var h=null,e=null,j=null,i=null,g=new d;_stateMachine=new c("Unresolved",{Unresolved:[["resolve",function(){h.call(e,function(){return _stateMachine.event.apply(_stateMachine,b.toArray(arguments))})}],["success",function(a){j=a;g.notify("success",a)},"Resolved"],["fail",function(a){i=a;g.notify("fail",a)},"Failed"],["addThen",function(a,e,b){g.watch(a,e,b)}]],Resolved:[["addThen",function(a,e,b){e.call(b,a==
"success"?j:i)}]],Failed:[["addThen",function(a,e,b){e.call(b,a=="success"?j:i)}]]});this.then=function(a,e,b,c){a instanceof Function&&(e instanceof Function?_stateMachine.event("addThen","success",e):_stateMachine.event("addThen","success",a,e));e instanceof Function&&_stateMachine.event("addThen","fail",e,b);b instanceof Function&&_stateMachine.event("addThen","fail",b,c)};this.resolve=function(){return!(!h||!_stateMachine.event("resolve"))};this.getState=function(){return _stateMachine.getCurrent()};
a instanceof Function&&(h=a,e=f)}});
define("StateMachine",["Tools"],function(c){function d(){var b={};this.add=function(a,c,d,e){var j=[];if(b[a])return false;return typeof a=="string"&&typeof c=="function"?(j[0]=c,typeof d=="object"&&(j[1]=d),typeof d=="string"&&(j[2]=d),typeof e=="string"&&(j[2]=e),b[a]=j,true):false};this.has=function(a){return!!b[a]};this.event=function f(f){var d=b[f];return d?(d[0].apply(d[1],c.toArray(arguments).slice(1)),d[2]):false}}return function(b,a){var f={},h="";this.init=function(a){return f[a]?(h=a,
true):false};this.add=function(a){return f[a]?false:f[a]=new d};this.get=function(a){return f[a]};this.getCurrent=function(){return h};this.event=function(a){var b=f[h].event.apply(f[h].event,c.toArray(arguments));return b===false?false:(h=b||h,true)};c.loop(a,function(a,b){var c=this.add(b);a.forEach(function(a){c.add.apply(null,a)})},this);this.init(b)}});
define("Store",["Observable","Tools"],function(c,d){return function(b){var a=d.clone(b)||{},f=new c,h=function(e){var b=d.objectsDiffs(e,a);["updated","deleted","added"].forEach(function(e){b[e].forEach(function(b){f.notify(e,b,a[b])})})};this.getNbItems=function(){return a instanceof Array?a.length:d.count(a)};this.get=function(e){return a[e]};this.has=function(e){return a.hasOwnProperty(e)};this.set=function(e,b){var c;return typeof e!="undefined"?(c=this.has(e),a[e]=b,c?f.notify("updated",e,a[e]):
f.notify("added",e,a[e]),true):false};this.del=function(e){return this.has(e)?(this.alter("splice",e,1)||(delete a[e],f.notify("deleted",e)),true):false};this.alter=function(e){var b,c;return a[e]?(c=d.clone(a),b=a[e].apply(a,Array.prototype.slice.call(arguments,1)),h(c),b):false};this.watch=function(a,b,c){return f.watch(a,b,c)};this.unwatch=function(a){return f.unwatch(a)};this.loop=function(b,c){d.loop(a,b,c)};this.reset=function(b){if(b instanceof Object){var c=d.clone(a);a=d.clone(b)||{};h(c);
return true}else return false}}});
define("Tools",function(){return{getGlobal:function(){return function(){return this}.call(null)},mixin:function(c,d,b){this.loop(c,function(a,f){if(!d[f]||!b)d[f]=c[f]});return d},count:function(c){var d=0;this.loop(c,function(){d++});return d},compareObjects:function(c,d){return Object.getOwnPropertyNames(c).sort().join("")==Object.getOwnPropertyNames(d).sort().join("")},toArray:function(c){return Array.prototype.slice.call(c)},loop:function(c,d,b){var a,f;if(c instanceof Object&&typeof d=="function"){if(f=
c.length)for(a=0;a<f;a++)d.call(b,c[a],a,c);else for(a in c)c.hasOwnProperty(a)&&d.call(b,c[a],a,c);return true}else return false},objectsDiffs:function(c,d){if(c instanceof Object&&d instanceof Object){var b=[],a=[],f=[],h=[];this.loop(d,function(e,d){e!==c[d]&&typeof c[d]!="undefined"?a.push(d):e===c[d]?b.push(d):typeof c[d]=="undefined"&&h.push(d)});this.loop(c,function(a,b){typeof d[b]=="undefined"&&f.push(b)});return{updated:a,unchanged:b,added:h,deleted:f}}else return false},jsonify:function(c){return c instanceof
Object?JSON.parse(JSON.stringify(c)):false},clone:function(c){return c instanceof Array?c.slice(0):typeof c=="object"&&c!==null&&!(c instanceof RegExp)?this.mixin(c,{}):c},getObjectsProperty:function(c,d){if(c instanceof Object&&typeof d=="string"){var b=d.split(".");b.unshift(c);return b.reduce(function(a,b){return a[b]})}else return false}}});
define("Transport",["Observable"],function(c){return function(d){var b,a=io,f=new c;this.connect=function(c){b=a.connect(c);return!!b};this.getSocket=function(){return b};this.on=function(a,c){b.on(a,c)};this.once=function(a,c){b.once(a,c)};this.emit=function(a,c,d){b.emit(a,c,d)};this.request=function(a,c,d,f){var g=Date.now()+Math.floor(Math.random()*1E6),k=function(){d.apply(f||null,arguments)};b[c.keptAlive?"on":"once"](g,k);c.__eventId__=g;b.emit(a,c);if(c.keptAlive)return function(){b.removeListener(g,
k)}};this.listen=function(a,b,c,d){var g=a+"/"+b,k,l;f.hasTopic(g)||(l=this.request(a,{path:b,method:"GET",keptAlive:true},function(a){f.notify(g,a)},this));k=f.watch(g,c,d);return{stop:function(){f.unwatch(k);f.hasTopic(g)||l()}}};this.getListenObservable=function(){return f};this.connect(d)}});
