define("Observable",["Tools"],function(c){function a(){var a={};this.watch=function(d,b,e){if(typeof b=="function"){var c=a[d]=a[d]||[];observer=[b,e];c.push(observer);return[d,c.indexOf(observer)]}else return false};this.unwatch=function(d){var b=d[0],d=d[1];return a[b]&&a[b][d]?(a[b][d]=null,true):false};this.notify=function(d){var b=a[d],e;if(b){for(e=b.length;e--;)b[e]&&b[e][0].apply(b[e][1]||null,c.toArray(arguments).slice(1));return true}else return false};this.hasObserver=function(d){return!(!d||
!a[d[0]]||!a[d[0]][d[1]])};this.unwatchAll=function(d){a[d]?delete a[d]:a={};return true}}return{create:function(){return new a}}});
define("StateMachine",function(){function c(){var c={},d="";this.init=function(b){return c[b]?(d=b,true):false};this.add=function(b){return c[b]?false:c[b]=new a};this.get=function(b){return c[b]};this.getCurrent=function(){return d};this.event=function(b,a){var f=c[d].event(b,a);return f===false?false:(d=f||d,true)}}function a(){var a={};this.add=function(d,b,c,f){var h=[];if(a[d])return false;return typeof d=="string"&&typeof b=="function"?(h[0]=b,typeof c=="object"&&(h[1]=c),typeof c=="string"&&
(h[2]=c),typeof f=="string"&&(h[2]=f),a[d]=h,true):false};this.has=function(d){return!!a[d]};this.event=function b(b,c){var f=a[b];return f?(f[0].call(f[1],c),f[2]):false}}return{create:function(a,d){var b=new c,e,f;for(e in d)d.hasOwnProperty(e)&&(f=b.add(e),d[e].forEach(function(b){f.add.apply(null,b)}));b.init(a);return b}}});define("StaticProxy",function(){function c(a){this.trap=function(c,d){var b=a[c];a[c]=function(){d();b()}}}return{create:function(a){return new c(a)}}});
define("TinyStore",["Observable","Tools"],function(c,a){function g(d){var b=JSON.parse(JSON.stringify(d||{})),e=c.create(),f=function(d){var c=a.objectsDiffs(d,a.jsonify(b));["updated","deleted","added"].forEach(function(a){c[a].forEach(function(d){e.notify(a,d,b[d])})})};this.getNbItems=function(){return a.count(b)};this.get=function(a){return b[a]};this.has=function(a){return b.hasOwnProperty(a)};this.set=function(a,d){var c;return typeof a!="undefined"?(c=this.has(a),b[a]=d,c?e.notify("updated",
a,b[a]):e.notify("added",a,b[a]),true):false};this.del=function(a){return this.has(a)?(delete b[a],e.notify("deleted",a),true):false};this.watch=function(a,b,d){return e.watch(a,b,d)};this.unwatch=function(a){return e.unwatch(a)};this.loop=function(d,c){a.loop(b,d,c)};this.reset=function(d){if(d instanceof Object){var c=a.jsonify(b);b=a.jsonify(d||{});f(c);return true}else return false};"push,pop,unshift,shift,slice,splice".split(",").forEach(function(d){this[d]=function(){var c=a.jsonify(b),e=b[d].apply(b,
arguments);f(c);return e}},this)}return{create:function(a){return new g(a)}}});
define("Tools",function(){return{getGlobal:function(){return function(){return this}.call(null)},mixin:function(c,a,g){this.loop(c,function(d,b){if(!a[b]||!g)a[b]=c[b]})},count:function(c){var a=0,g;for(g in c)c.hasOwnProperty(g)&&a++;return a},compareObjects:function(c,a){return Object.getOwnPropertyNames(c).sort().join("")==Object.getOwnPropertyNames(a).sort().join("")},toArray:function(c){return Array.prototype.slice.call(c)},loop:function(c,a,g){if(c instanceof Object&&typeof a=="function"){var d;
if(c instanceof Array)c.forEach(a,g);else for(d in c)c.hasOwnProperty(d)&&a.call(g,c[d],d,c);return true}else return false},objectsDiffs:function(c,a){if(c instanceof Object&&a instanceof Object){var g=[],d=[],b=[],e=[];this.loop(a,function(a,b){a!==c[b]&&typeof c[b]!="undefined"?d.push(b):a===c[b]?g.push(b):typeof c[b]=="undefined"&&e.push(b)});this.loop(c,function(d,c){typeof a[c]=="undefined"&&b.push(c)});return{updated:d,unchanged:g,added:e,deleted:b}}else return false},jsonify:function(c){return c instanceof
Object?JSON.parse(JSON.stringify(c)):false}}});
define("Transport",function(){function c(){var a,c=io;this.connect=function(d){a=c.connect(d);return!!a};this.getSocket=function(){return a};this.on=function(d,b){a.on(d,b)};this.once=function(d,b){a.once(d,b)};this.emit=function(d,b,c){a.emit(d,b,c)};this.request=function(d,b,c){var f=+new Date+Math.floor(Math.random()*1E6);a.once(f,c);b.__eventId__=f;a.emit(d,b)};this.listen=function(d,b,c){var f=+new Date+Math.floor(Math.random()*1E6);a.on(f,c);b.__eventId__=f;a.emit(d,b);return{stop:function(){a.removeListener(f,
c)}}}}return{create:function(a){var g=new c(a);g.connect(a);return g}}});
