define("CouchDBStore",["Store","Tools"],function(a){function c(){var c=null,b={};this.sync=function(d,a,h){return typeof d=="string"&&typeof a=="string"&&typeof h=="string"?(c.request("CouchDB",{method:"GET",path:"/"+d+"/_design/"+a+"/_view/"+h+"?update_seq=true"},function(g){g=JSON.parse(g);b={total_rows:g.total_rows,update_seq:g.update_seq,offset:g.offset};this.reset(g.rows);c.listen("CouchDB",{method:"GET",path:"/"+d+"/_changes?feed=continuous&heartbeat=20000&since="+b.update_seq},function(b){if(b==
"\n")return false;b=JSON.parse(b);c.request("CouchDB",{method:"GET",path:"/"+d+"/_design/"+a+"/_view/"+h+'?key="'+b.id+'"'},function(b){b=JSON.parse(b);this.set(b.offset,b.rows[0])},this)},this)},this),true):false};this.getDBInfo=function(c){return b[c]};this.setTransport=function(b){return b&&typeof b.listen=="function"&&typeof b.request?(c=b,true):false};this.getTransport=function(){return c}}c.prototype=new a;return c});
define("Observable",["Tools"],function(a){return function(){var c={};this.watch=function(a,b,d){if(typeof b=="function"){var e=c[a]=c[a]||[];observer=[b,d];e.push(observer);return[a,e.indexOf(observer)]}else return false};this.unwatch=function(a){var b=a[0],a=a[1];return c[b]&&c[b][a]?(c[b][a]=null,true):false};this.notify=function(f){var b=c[f],d;if(b){for(d=b.length;d--;)b[d]&&b[d][0].apply(b[d][1]||null,a.toArray(arguments).slice(1));return true}else return false};this.hasObserver=function(a){return!(!a||
!c[a[0]]||!c[a[0]][a[1]])};this.unwatchAll=function(a){c[a]?delete c[a]:c={};return true}}});
define("StateMachine",["Tools"],function(a){function c(){var a={};this.add=function(b,c,e,h){var g=[];if(a[b])return false;return typeof b=="string"&&typeof c=="function"?(g[0]=c,typeof e=="object"&&(g[1]=e),typeof e=="string"&&(g[2]=e),typeof h=="string"&&(g[2]=h),a[b]=g,true):false};this.has=function(b){return!!a[b]};this.event=function d(d,c){var h=a[d];return h?(h[0].call(h[1],c),h[2]):false}}return function(f,b){var d={},e="";this.init=function(b){return d[b]?(e=b,true):false};this.add=function(b){return d[b]?
false:d[b]=new c};this.get=function(b){return d[b]};this.getCurrent=function(){return e};this.event=function(b,a){var c=d[e].event(b,a);return c===false?false:(e=c||e,true)};a.loop(b,function(b,a){var c=this.add(a);b.forEach(function(b){c.add.apply(null,b)})},this);this.init(f)}});define("StaticProxy",function(){return function(a){this.trap=function(c,f){var b=a[c];a[c]=function(){f();b()}}}});
define("Store",["Observable","Tools"],function(a,c){return function(f){var b=c.clone(f)||{},d=new a,e=function(a){var g=c.objectsDiffs(a,b);["updated","deleted","added"].forEach(function(a){g[a].forEach(function(c){d.notify(a,c,b[c])})})};this.getNbItems=function(){return b instanceof Array?b.length:c.count(b)};this.get=function(a){return b[a]};this.has=function(a){return b.hasOwnProperty(a)};this.set=function(a,c){var e;return typeof a!="undefined"?(e=this.has(a),b[a]=c,e?d.notify("updated",a,b[a]):
d.notify("added",a,b[a]),true):false};this.del=function(a){return this.has(a)?(this.alter("splice",a,1)||delete b[a],d.notify("deleted",a),true):false};this.alter=function(a){var d,f;return b[a]?(f=c.clone(b),d=b[a].apply(b,Array.prototype.slice.call(arguments,1)),e(f),d):false};this.watch=function(a,b,c){return d.watch(a,b,c)};this.unwatch=function(a){return d.unwatch(a)};this.loop=function(a,d){c.loop(b,a,d)};this.reset=function(a){if(a instanceof Object){var d=c.clone(b);b=c.clone(a)||{};e(d);
return true}else return false}}});
define("Tools",function(){return{getGlobal:function(){return function(){return this}.call(null)},mixin:function(a,c,f){this.loop(a,function(b,d){if(!c[d]||!f)c[d]=a[d]});return c},count:function(a){var c=0;this.loop(a,function(){c++});return c},compareObjects:function(a,c){return Object.getOwnPropertyNames(a).sort().join("")==Object.getOwnPropertyNames(c).sort().join("")},toArray:function(a){return Array.prototype.slice.call(a)},loop:function(a,c,f){var b;if(a instanceof Object&&typeof c=="function"){if(a instanceof
Array)a.forEach(c,f);else for(b in a)a.hasOwnProperty(b)&&c.call(f,a[b],b,a);return true}else return false},objectsDiffs:function(a,c){if(a instanceof Object&&c instanceof Object){var f=[],b=[],d=[],e=[];this.loop(c,function(c,d){c!==a[d]&&typeof a[d]!="undefined"?b.push(d):c===a[d]?f.push(d):typeof a[d]=="undefined"&&e.push(d)});this.loop(a,function(a,b){typeof c[b]=="undefined"&&d.push(b)});return{updated:b,unchanged:f,added:e,deleted:d}}else return false},jsonify:function(a){return a instanceof
Object?JSON.parse(JSON.stringify(a)):false},clone:function(a){return a instanceof Array?a.slice(0):typeof a=="object"&&a!==null&&!(a instanceof RegExp)?this.mixin(a,{}):a}}});
define("Transport",function(){return function(a){var c,f=io;this.connect=function(a){c=f.connect(a);return!!c};this.getSocket=function(){return c};this.on=function(a,d){c.on(a,d)};this.once=function(a,d){c.once(a,d)};this.emit=function(a,d,e){c.emit(a,d,e)};this.request=function(a,d,e,f){var g=Date.now()+Math.floor(Math.random()*1E6),i=function(){e.apply(f||null,arguments)};c[d.keptAlive?"on":"once"](g,i);d.__eventId__=g;c.emit(a,d);if(d.keptAlive)return{stop:function(){c.removeListener(g,i)}}};this.listen=
function(a,c,e,f){c.keptAlive=true;return this.request(a,c,e,f)};this.connect(a)}});
