define("Olives/DomUtils",function(){return{getNodes:function(b,f){return b instanceof HTMLElement?(b.parentNode||document.createDocumentFragment().appendChild(b),b.parentNode.querySelectorAll(f||"*")):false}}});define("Olives/List",["Olives/OObject","Olives/Model-plugin"],function(b,f){function e(){this.template="<ul data-model='toList'><li data-model='toText'></li></ul>";this.plugins.add("model",new f(this.model))}return function(f){e.prototype=new b(f);return new e}});
define("Olives/Model-plugin",["Store","Observable","Tools","Olives/DomUtils"],function(b,f,e,h){return function(i){var d=null,j=new f;this.setModel=function(c){return c instanceof b?(d=c,d.watch("updated",function(a,g){j.notify(a,g)}),d.watch("added",function(a,g){j.notify(a,g)}),true):false};this.getModel=function(){return d};this.ItemRenderer=function(c){var a=null;this.set=function(g){a=g;return true};this.get=function(){return a};this.associate=function(g,c){var d=a.cloneNode(true),b=h.getNodes(d,
"[data-"+c+"]");e.loop(b,function(a){a&&(a.dataset[c+".id"]=g)});return d};this.set(c)};this.toList=function(c){var a,g=new this.ItemRenderer(c.childNodes[0]);a=document.createDocumentFragment();d.loop(function(c,d){a.appendChild(this.plugins.apply(g.associate(d,this.plugins.name)))},this);c.replaceChild(a,c.childNodes[0]);d.watch("added",function(a){c.insertBefore(this.plugins.apply(g.associate(a,this.plugins.name)),c.childNodes[a])},this);d.watch("deleted",function(a){c.replaceChild(document.createTextNode(""),
c.childNodes[a])})};this.toText=function(c,a){var a=a||"",g=c.dataset[this.plugins.name+".id"],b=a.split("."),f=g||b.shift(),h=g?a:b.join(".");if(g=e.getObjectsProperty(d.get(f),h))c.innerHTML=g;j.watch(f,function(a){c.innerHTML=e.getObjectsProperty(a,h)})};this.setModel(i)}});
define("Olives/OObject",["StateMachine","Store","Olives/Plugins"],function(b,f,e){return function(h){var i=function(a){a=a.UI;if(a.template)a.dom=j,typeof a.template=="string"?a.dom.innerHTML=a.template:a.template instanceof HTMLElement&&a.dom.appendChild(a.template),a.plugins.apply(a.dom),a.onRender&&a.onRender();else throw Error("UI.template must be set prior to render");},d=function(a){var c=a.UI;a.params&&a.params.appendChild(c.dom);c.onPlace&&c.onPlace()},j=document.createElement("div"),c=new b("Init",
{Init:[["render",i,this,"Rendered"],["place",function(a){i(a);d(a)},this,"Rendered"]],Rendered:[["place",d,this],["render",i,this]]});this.model=h instanceof f?h:new f;this.plugins=new e;this.dom=this.template=null;this.onRender=function(){};this.action=function(a,d){c.event(a,{UI:this,params:d})};this.onPlace=function(){}}});
define("Olives/Plugins",["Tools","Olives/DomUtils"],function(b,f){return function(){var e={},h=function(d){return d.trim()},i=function(d,b,c){b.split(";").forEach(function(a){var b=a.split(":"),a=b[0].trim(),b=b[1]?b[1].split(",").map(h):[];b.unshift(d);e[c]&&e[c][a]&&e[c][a].apply(e[c],b)})};this.add=function(d,b){var c=this;return typeof d=="string"&&typeof b=="object"&&b?(e[d]=b,b.plugins={name:d,apply:function(){return c.apply.apply(c,arguments)}},true):false};this.get=function(b){return e[b]};
this.del=function(b){return delete e[b]};this.apply=function(d){var e;return d instanceof HTMLElement?(e=f.getNodes(d),b.loop(b.toArray(e),function(c){b.loop(c.dataset,function(a,b){i(c,a,b)})}),d):false}}});define("Olives/Text",["Olives/OObject","Olives/Model-plugin"],function(b,f){function e(b){this.template="<p data-model='toText:content'></p>";this.model.reset(b);this.plugins.add("model",new f(this.model))}return function(f){e.prototype=new b;return new e(f)}});
define("Olives/Type-plugin",function(){return function(){this.ui=function(b,f){require([f],function(e){(new e).action("place",b)})}}});
